INSERT INTO whitelist_alumnos (matricula) VALUES ('A00123456');
INSERT INTO whitelist_alumnos (matricula) VALUES ('A00987654');
INSERT INTO whitelist_alumnos (matricula) VALUES ('A00555555');
INSERT INTO whitelist_alumnos (matricula) VALUES ('A00112233');
INSERT INTO whitelist_alumnos (matricula) VALUES ('A00101010');
INSERT INTO whitelist_alumnos (matricula) VALUES ('A00202020');
INSERT INTO whitelist_alumnos (matricula) VALUES ('A00303030');
INSERT INTO whitelist_alumnos (matricula) VALUES ('admin');

INSERT INTO app_users (matricula, full_name, email, password, role, is_sanctioned) VALUES ('admin', 'Administrador del Sistema', 'admin@test.com', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'ROLE_ADMIN', false);
INSERT INTO app_users (matricula, full_name, email, password, role, is_sanctioned) VALUES ('A00123456', 'Juan Pérez González', 'juan@test.com', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'ROLE_STUDENT', false);
INSERT INTO app_users (matricula, full_name, email, password, role, is_sanctioned) VALUES ('A00987654', 'María Rodríguez', 'maria@test.com', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'ROLE_STUDENT', true);
INSERT INTO app_users (matricula, full_name, email, password, role, is_sanctioned) VALUES ('A00555555', 'Carlos López Martínez', 'carlos@test.com', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'ROLE_STUDENT', false);
INSERT INTO app_users (matricula, full_name, email, password, role, is_sanctioned) VALUES ('A00112233', 'Ana García Fernández', 'ana@test.com', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'ROLE_STUDENT', false);
INSERT INTO app_users (matricula, full_name, email, password, role, is_sanctioned) VALUES ('A00101010', 'Pedro Martínez Ruiz', 'pedro@test.com', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'ROLE_STUDENT', false);
INSERT INTO app_users (matricula, full_name, email, password, role, is_sanctioned) VALUES ('A00202020', 'Laura Torres Sánchez', 'laura@test.com', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'ROLE_STUDENT', false);
INSERT INTO app_users (matricula, full_name, email, password, role, is_sanctioned) VALUES ('P001', 'Dr. Roberto Hernández', 'roberto@test.com', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6', 'ROLE_PROFFESOR', false);

INSERT INTO software (name, version) VALUES ('Android Studio', '2023.1');
INSERT INTO software (name, version) VALUES ('Visual Studio Code', '1.85');
INSERT INTO software (name, version) VALUES ('Docker Desktop', '4.26');
INSERT INTO software (name, version) VALUES ('IntelliJ IDEA', '2023.3');
INSERT INTO software (name, version) VALUES ('PostgreSQL', '16');
INSERT INTO software (name, version) VALUES ('Unity Hub', '2023.2');
INSERT INTO software (name, version) VALUES ('Python', '3.12');
INSERT INTO software (name, version) VALUES ('Node.js', '20.0 LTS');
INSERT INTO software (name, version) VALUES ('Xcode', '15.0');

INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-HIGH-001', 'Dell XPS 15 (i9, 32GB)', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-HIGH-002', 'MacBook Pro M3 Max', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-HIGH-003', 'Alienware m15', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-HIGH-004', 'Asus ROG Zephyrus', 'IN_USE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-STD-001', 'MacBook Air M2', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-STD-002', 'Lenovo ThinkPad T14', 'IN_USE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-STD-003', 'Dell Latitude', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-STD-004', 'HP EliteBook 840', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-STD-005', 'Acer Swift 5', 'IN_USE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-SRV-001', 'ThinkPad X1 Carbon', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-SRV-002', 'HP EliteBook', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-SRV-003', 'System76 Lemur Pro', 'AVAILABLE');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-BROKEN-01', 'HP Pavilion Legacy', 'EN_REPARACION');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-BROKEN-02', 'Dell Inspiron', 'MAINTENANCE_REQUIRED');
INSERT INTO laptops (serial_number, model, status) VALUES ('LPT-LOST-01', 'MacBook Pro 2019', 'INACTIVE');

INSERT INTO laptop_software (laptop_id, software_id) VALUES (1, 1);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (1, 2);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (1, 4);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (2, 9);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (2, 2);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (3, 6);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (3, 2);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (5, 2);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (5, 8);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (6, 2);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (6, 7);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (7, 2);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (7, 8);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (8, 2);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (9, 2);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (10, 3);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (10, 5);
INSERT INTO laptop_software (laptop_id, software_id) VALUES (11, 3);

INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (2, 5, DATEADD('DAY', -6, CURRENT_TIMESTAMP), DATEADD('DAY', -6, DATEADD('HOUR', 2, CURRENT_TIMESTAMP)), 'COMPLETED', 'Programación Web', 'Dr. Hernández', 'RES-001');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (4, 6, DATEADD('DAY', -6, CURRENT_TIMESTAMP), DATEADD('DAY', -6, DATEADD('HOUR', 3, CURRENT_TIMESTAMP)), 'COMPLETED', 'Bases de Datos', 'Dra. López', 'RES-002');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (5, 7, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, DATEADD('HOUR', 4, CURRENT_TIMESTAMP)), 'COMPLETED', 'Redes', 'Ing. García', 'RES-003');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (6, 1, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, DATEADD('HOUR', 2, CURRENT_TIMESTAMP)), 'COMPLETED', 'Desarrollo Móvil', 'Dr. Hernández', 'RES-004');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (2, 2, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, DATEADD('HOUR', 1, CURRENT_TIMESTAMP)), 'COMPLETED', 'iOS Dev', 'Dr. Hernández', 'RES-005');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (4, 10, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, DATEADD('HOUR', 5, CURRENT_TIMESTAMP)), 'COMPLETED', 'DevOps', 'Ing. Martínez', 'RES-006');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (5, 5, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, DATEADD('HOUR', 2, CURRENT_TIMESTAMP)), 'COMPLETED', 'Programación Web', 'Dr. Hernández', 'RES-007');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (6, 3, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, DATEADD('HOUR', 3, CURRENT_TIMESTAMP)), 'COMPLETED', 'Gráficas Computacionales', 'Dra. Ruiz', 'RES-008');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (7, 4, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, DATEADD('HOUR', 2, CURRENT_TIMESTAMP)), 'COMPLETED', 'Algoritmos', 'Dr. Pérez', 'RES-009');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (2, 11, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, DATEADD('HOUR', 1, CURRENT_TIMESTAMP)), 'COMPLETED', 'Sistemas Operativos', 'Ing. García', 'RES-010');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (4, 1, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, DATEADD('HOUR', 4, CURRENT_TIMESTAMP)), 'COMPLETED', 'Android Studio', 'Dr. Hernández', 'RES-011');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (5, 8, DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -2, DATEADD('HOUR', 2, CURRENT_TIMESTAMP)), 'COMPLETED', 'Programación Web', 'Dr. Hernández', 'RES-012');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (6, 9, DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -2, DATEADD('HOUR', 3, CURRENT_TIMESTAMP)), 'COMPLETED', 'Proyecto Final', 'Dra. López', 'RES-013');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (2, 2, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, DATEADD('HOUR', 2, CURRENT_TIMESTAMP)), 'COMPLETED', 'iOS Dev', 'Dr. Hernández', 'RES-014');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (7, 10, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, DATEADD('HOUR', 4, CURRENT_TIMESTAMP)), 'COMPLETED', 'DevOps', 'Ing. Martínez', 'RES-015');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (2, 6, DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), DATEADD('HOUR', 2, CURRENT_TIMESTAMP), 'ACTIVE', 'Bases de Datos', 'Dra. López', 'RES-016');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (4, 4, DATEADD('MINUTE', -15, CURRENT_TIMESTAMP), DATEADD('HOUR', 2, CURRENT_TIMESTAMP), 'ACTIVE', 'Algoritmos', 'Dr. Pérez', 'RES-017');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (5, 9, DATEADD('MINUTE', -45, CURRENT_TIMESTAMP), DATEADD('HOUR', 2, CURRENT_TIMESTAMP), 'ACTIVE', 'Proyecto Final', 'Dra. López', 'RES-018');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (2, 3, DATEADD('HOUR', 1, CURRENT_TIMESTAMP), DATEADD('HOUR', 5, CURRENT_TIMESTAMP), 'APPROVED', 'Gráficas Computacionales', 'Dra. Ruiz', 'RES-019');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (6, 1, DATEADD('HOUR', 1, CURRENT_TIMESTAMP), DATEADD('HOUR', 3, CURRENT_TIMESTAMP), 'APPROVED', 'Desarrollo Móvil', 'Dr. Hernández', 'RES-020');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (7, 5, DATEADD('HOUR', 2, CURRENT_TIMESTAMP), DATEADD('HOUR', 4, CURRENT_TIMESTAMP), 'APPROVED', 'Programación Web', 'Dr. Hernández', 'RES-021');
INSERT INTO reservations (user_id, laptop_id, start_time, end_time, status, subject, professor, batch_id) VALUES (2, 7, DATEADD('HOUR', -10, CURRENT_TIMESTAMP), DATEADD('HOUR', -8, CURRENT_TIMESTAMP), 'OVERDUE', 'Redes', 'Ing. García', 'RES-022');

INSERT INTO incidents (laptop_id, description, severity, reported_at, reporter_id) VALUES (13, 'La pantalla parpadea constantemente', 'HIGH', DATEADD('DAY', -5, CURRENT_TIMESTAMP), 2);
INSERT INTO incidents (laptop_id, description, severity, reported_at, reporter_id) VALUES (14, 'La batería se descarga en 15 minutos', 'MEDIUM', DATEADD('DAY', -3, CURRENT_TIMESTAMP), 4);
INSERT INTO incidents (laptop_id, description, severity, reported_at, reporter_id) VALUES (15, 'Extraviado durante evento', 'CRITICAL', DATEADD('DAY', -10, CURRENT_TIMESTAMP), 2);
INSERT INTO incidents (laptop_id, description, severity, reported_at, reporter_id) VALUES (6, 'La tecla "A" se queda pegada', 'LOW', DATEADD('DAY', -1, CURRENT_TIMESTAMP), 5);
INSERT INTO incidents (laptop_id, description, severity, reported_at, reporter_id) VALUES (2, 'Rasguños leves en la carcasa', 'LOW', DATEADD('DAY', -8, CURRENT_TIMESTAMP), 6);
